# Generated by Django 4.2 on 2024-11-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_artist',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur est un artiste"),
        ),
    ]
