# Generated by Django 4.2 on 2024-11-06 05:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artistes', '0003_alter_artistes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id_art', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=5, null=True)),
                ('file', models.FileField(upload_to='arts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'mp4', 'mp3'], message='Arts doit etre soit musique .mp3 ou .mp4 soit image :. jpg ou .png soit vidéo .mp4')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arts', to='artistes.artistes')),
            ],
        ),
    ]
