# Generated by Django 4.2 on 2024-11-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='type',
        ),
    ]
