# Generated by Django 4.2 on 2024-11-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artistes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistes',
            name='bio',
        ),
    ]
