# Generated by Django 4.2 on 2024-11-06 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artistes', '0002_remove_artistes_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistes',
            options={'verbose_name': 'Artiste', 'verbose_name_plural': 'Artiste'},
        ),
    ]
