# Generated by Django 4.2 on 2024-11-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('ID_vente', models.AutoField(primary_key=True, serialize=False)),
                ('date_paiement', models.DateField()),
                ('prix_paiement', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
