# Generated by Django 5.1.3 on 2024-11-11 22:57

import django.db.models.deletion
import prjetse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paiement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('ID_art', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='art', max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo'), ('MUSIQUE', 'Musique')], max_length=50)),
                ('categorie', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('fichier', models.FileField(default='path/to/default/file', upload_to='prjetse/', validators=[prjetse.models.validate_art_file_type, prjetse.models.validate_max_size])),
                ('price', models.FloatField()),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arts', to='paiement.paiement')),
            ],
        ),
    ]
